config/routes.rb
ChordateUi::Application.routes.draw do
  resources :users,     :only => [:new, :create]
  resources :sessions,  :only => [:new, :create]

  resources :applications, :only => [:new, :index, :create, :show] do
    resources :users,   :only => [:index]
    resources :events,  :only => [:index]
    resources :filters, :only => [:index]
    resources :invites, :only => [:show, :create, :update]
  end

  namespace :v1, :module => :api do
    resources :applications, :only => [] do
      resources :events, :only => [:create, :update]
    end
  end

  get '/v1/applications/:application_id/events', :to => 'events#index'

  get '/dashboard' => 'dashboards#index'

  root :to => 'sessions#new'
end

app/models/application.rb
require_all "securerandom"

class Application < ActiveRecord::Base
  TOKEN = "%010d%020d"

  belongs_to :account
  belongs_to :user

  has_many :events
  has_many :application_users
  has_many :users, :through => :application_users

  before_validation -> { self.account = user.account }, :on => :create, :unless => -> { account.present? }

  validates :name, :user, :presence => true

  before_create -> { self.token = generate_token }
  after_create  -> { self.users << user }

  private

  def generate_token
    (TOKEN % [Time.now.to_i, user.id]).to_i.to_s(36) + SecureRandom.hex(9)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate!

  def user
    @user ||= begin
      User.where(:token => _user_token).first.tap_if(:present?) do |user|
        params[:user] = user
      end
    end
  end

  def user?
    user.present?
  end

  def account
    @account ||= begin
      (user? && user.account ||
        application? && application.account).tap_if(:present?) do |account|
          params[:account] = account
      end
    end
  end

  def account?
    account.present?
  end

  def application
    @application ||= begin
      if (app_id = params[:application_id].presence)
        params[:application] = (user? ? user.applications : Application).find(app_id)
      end
    end
  end

  def application?
    application.present?
  end

  def set_cookie
    cookies.signed[:token] = {
      :value => @item.token,
      :expires => 3.weeks.from_now
    }

    true
  end

  def render_error
    if params[:action] == "create"
      render :json => {:errors => @item.errors.full_messages}, :status => 422
    end
  end

  helper_method :user, :user?, :account, :account?, :application, :application?

  private

  def authenticate!
    unless user?
      redirect_to new_session_path
    end
  end

  def _user_token
    cookies.signed[:token].presence || params[:token]
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def new
  end

  def index
  end

  def create
    @item = Application.new(params.slice(:name, :user))

    if(decorator = ApplicationDecorator.new(@item)).save
      render :json => decorator, :status => :created
    else
      render_error
    end
  end

  def show
    params[:application_id] = params.delete(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/index.html.erb
<div>
  <div class='header'>
    <h2 class='title'>
      <%= I18n.t("applications.index.title") %>
    </h2>
  </div>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Added</th>
        <th>Last Changed By</th>
        <th>API Token</th>
        <th>Detail</th>
      </tr>
    </thead>
    <tbody>
    <% user.applications.includes(:user).each do |application| %>
      <tr class='application' id="application_<%= application.id %>">
        <td><%= link_to application.name, application_path(application) %></td>
        <td><%= time_ago_in_words(application.created_at) %> ago</td>
        <td><%= application.user.name %></td>
        <td><%= "#{application.id}:#{application.token}" %></td>
        <td><%= link_to I18n.t("applications.index.go_to_app"), application_path(application) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/applications/new.html.erb
<div id='applications-new' class='new'></div>

<script type='text/javascript'>
  (new c.v.ApplicationsNewView({el: '#applications-new'})).render();
</script>

app/views/applications/show.html.erb
<div>
  <div id='users'></div>
</div>

<script type='text/javascript'>
  c.data.application = new Backbone.Model(<%= raw(ApplicationDecorator.new(application).to_json) %>);

  (new c.v.UsersListView({el: "#users"})).render();
</script>